slam_toolbox:
  ros__parameters:
    # Frame parameters
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    
    # Map parameters
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 2.0
    minimum_time_interval: 0.3
    transform_timeout: 0.3
    
    # Laser parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 30
    scan_buffer_maximum_scan_distance: 1.5
    
    # Throttle settings to prevent queue overflow
    #throttle_scans: 3
    
    # Optimization parameters
    use_response_expansion: true
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 5
    loop_match_maximum_variance_coarse: 2.0
    loop_match_minimum_response_coarse: 0.1
    loop_match_minimum_response_fine: 0.1
    
    # Correlation parameters
    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.05
    
    # Occupancy grid parameters
    occupancy_grid_variance_publish: 0.0
    occupied_space_weight: 10.0
    minimum_move_scan: 0.1
    
    # Mode
    mode: mapping
    
    # Link matching parameters
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5